version: "3.7"
services:
    nginx:
      build:
        context: ./localNginx #ローカル開発用です。HTTPSポートは公開しません 
        dockerfile: Dockerfile
      ports:
          - target: 80
            published: 8080
            protocol: tcp

    backend:
      init: true
      build:
        context: ../development/backend
        dockerfile: Dockerfile

    frontend:
      build:
        context: ./dummyFrontend #dummyFrontendはダミーのhtmlのみ返却します。
        dockerfile: Dockerfile

    mysql:
      build:
        context: ./localMysql
        dockerfile: Dockerfile
      ports:
        - "3306:3306"
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_DATABASE: app
        MYSQL_USER: backend
        MYSQL_PASSWORD : backend

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - PMA_USER=backend
        - PMA_PASSWORD=backend
      ports:
        - 8888:80

